// Copyright 2026 The Faros Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Package kro is the provider-side client for a central kro (Kube
// Resource Orchestrator) cluster. The provider lists kro's
// ResourceGraphDefinitions (RGDs) to populate the template catalog,
// and creates instances of the dynamically-generated CRDs each RGD
// owns when a tenant provisions a template.
//
// kro upstream: https://github.com/kro-run/kro (and the multicluster
// fork at github.com/faroshq/kro-multicluster). The RGD's spec.schema
// uses kro's "SimpleSchema" DSL — a flat `field: type` map with
// optional `| required=true | default=…` qualifiers — NOT JSON-schema.
// schema.go converts SimpleSchema to a JSON-schema-shaped object so
// the portal's DynamicForm can render inputs without learning kro's
// DSL.
package kro

import (
	"time"

	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Template is a portal-shaped view of a kro ResourceGraphDefinition.
// Hides the kro-internal fields the UI does not need and exposes the
// JSON-schema-shaped InputsSchema the DynamicForm consumes.
type Template struct {
	// Name is the RGD's metadata.name; it doubles as the template
	// identifier used in API URLs (POST /api/instances {templateName}).
	Name string `json:"name"`
	// DisplayName, Description, Category, Cloud are pulled from the
	// RGD's labels/annotations (see kedge.faros.sh/* convention in
	// docs/credentials.md). Empty strings are valid — the UI falls
	// back to Name and the "Other" category.
	DisplayName string `json:"displayName"`
	Description string `json:"description"`
	Category    string `json:"category,omitempty"`
	Cloud       string `json:"cloud,omitempty"`
	// Version is read from the kedge.faros.sh/template-version label.
	// Required by POST /api/instances so we never silently provision
	// against a different RGD generation than the user previewed.
	Version string `json:"version,omitempty"`
	// IconURL is an optional asset URL stored in the
	// kedge.faros.sh/icon-url annotation. The portal falls back to a
	// generic icon when empty.
	IconURL string `json:"iconURL,omitempty"`
	// Backend identifies which provisioning engine handles this
	// template — currently always "kro" (this provider's only
	// implementation) but exposed in the API now so a future
	// dispatch layer can route to "terraform", "cloud", etc. without
	// breaking the wire format. The UI ignores it today; treat it as
	// internal metadata until the multi-backend story lands.
	Backend string `json:"backend,omitempty"`
	// InstanceGVR is the GroupVersionResource of the dynamically-
	// generated CRD this RGD installs in the central kro cluster.
	// Derived from RGD.spec.schema.{group,version,kind} on read.
	InstanceGVR schema.GroupVersionResource `json:"-"`
	// InstanceKind is the Kind of the generated CRD, surfaced so the
	// portal can render "Provisioning a Postgres…" style copy
	// without re-deriving it.
	InstanceKind string `json:"kind"`
	// InputsSchema is a JSON-schema-shaped object describing the
	// fields accepted under spec on an instance. Generated by
	// schema.ConvertSimpleSchema. Top-level keys: type ("object"),
	// properties (per-field), required ([]string).
	InputsSchema map[string]any `json:"inputsSchema"`
	// SampleValues is an optional example payload provided by the RGD
	// author via the kedge.faros.sh/sample-values annotation. The
	// portal uses it to seed the form so users see a working example.
	SampleValues map[string]any `json:"sampleValues,omitempty"`
}

// Instance is a portal-shaped view of a kro RGD instance CR in the
// central cluster. Fields are populated from
// .metadata + .spec + a small set of well-known status fields kro
// writes onto every instance (Conditions, Children).
type Instance struct {
	Name      string                 `json:"name"`
	Namespace string                 `json:"namespace"`
	Template  string                 `json:"template"`
	Phase     string                 `json:"phase"`
	Message   string                 `json:"message,omitempty"`
	Conditions []InstanceCondition   `json:"conditions,omitempty"`
	Children  []InstanceChild        `json:"children,omitempty"`
	Values    map[string]any         `json:"values,omitempty"`
	CreatedAt time.Time              `json:"createdAt"`
}

// InstanceCondition mirrors metav1.Condition with a JSON-shape the
// portal can render directly.
type InstanceCondition struct {
	Type    string    `json:"type"`
	Status  string    `json:"status"`
	Reason  string    `json:"reason,omitempty"`
	Message string    `json:"message,omitempty"`
	Time    time.Time `json:"time,omitempty"`
}

// InstanceChild is one of the child resources kro materialized for an
// instance. Kept thin: surface enough that the user can recognize
// "what got created", not enough to be an SDK in disguise.
type InstanceChild struct {
	APIVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Namespace  string `json:"namespace,omitempty"`
	Phase      string `json:"phase,omitempty"`
}

// CreateInstanceRequest is the broker payload: a template reference
// plus the values the user filled into the DynamicForm.
type CreateInstanceRequest struct {
	TemplateName    string         `json:"templateName"`
	TemplateVersion string         `json:"templateVersion"`
	Name            string         `json:"name"`
	Values          map[string]any `json:"values"`
}

// RGD label/annotation contract — platform admins publishing templates
// MUST follow this when they ship RGDs into the central kro cluster.
// Documented for end users in docs/credentials.md.
const (
	// LabelExpose gates RGD visibility. Only RGDs labeled
	// "true" appear in the catalog. Lets admins stage drafts.
	LabelExpose = "kedge.faros.sh/expose"
	// LabelTemplateName is the catalog-stable slug. Defaults to
	// RGD metadata.name; override when the kro name has to change but
	// you want consumers' bookmarks to keep working.
	LabelTemplateName = "kedge.faros.sh/template-name"
	// LabelTemplateVersion pins a semver to the RGD revision. Required
	// in POST /api/instances so a chart bump doesn't silently change
	// what gets provisioned.
	LabelTemplateVersion = "kedge.faros.sh/template-version"
	// LabelCategory lets the catalog UI render filter chips.
	LabelCategory = "kedge.faros.sh/category"
	// LabelCloud is the target cloud (aws/gcp/azure/k8s/...) — used
	// for credential schema validation and filtering.
	LabelCloud = "kedge.faros.sh/cloud"

	AnnotationDisplayName  = "kedge.faros.sh/display-name"
	AnnotationDescription  = "kedge.faros.sh/description"
	AnnotationIconURL      = "kedge.faros.sh/icon-url"
	AnnotationSampleValues = "kedge.faros.sh/sample-values"

	// LabelTenant is set on every instance CR + the credentials Secret
	// the provider creates on the user's behalf, so list operations
	// can be scoped per-tenant via a label selector. The value is the
	// tenant kcp workspace path (e.g. root:kedge:orgs:{uuid}).
	LabelTenant = "kedge.faros.sh/tenant"
	// LabelUser records the User CR name of the human who provisioned
	// the instance. Audit-only — never used for authz.
	LabelUser = "kedge.faros.sh/user"
	// LabelTemplate records which template (by Name) produced the
	// instance, so reverse-lookups don't require parsing the CR's
	// APIVersion/Kind back into a template name.
	LabelTemplate = "kedge.faros.sh/template"
	// LabelManagedBy is set on the per-tenant namespace and any
	// helper resources the provider creates in central kro.
	LabelManagedBy      = "kedge.faros.sh/managed-by"
	ManagedByValue      = "infrastructure-provider"
	ManagedByNamespace  = "kedge-tenants"
)

// RGD is the kro upstream type expressed as a plain GVR. The provider
// reads RGDs via the dynamic client so we don't take a runtime
// dependency on the kro Go module.
var RGDGroupVersionResource = schema.GroupVersionResource{
	Group:    "kro.run",
	Version:  "v1alpha1",
	Resource: "resourcegraphdefinitions",
}
